[tool.poetry]
name = "marketing_idea_generator_agent"
version = "0.1.0"
description = ""
authors = ["Jeremy Wortz <jwortz@google.com>"]
readme = "README.md"
package-mode = true 

[tool.poetry.dependencies]
python = "^3.12"
ipython = "^9.1.0"
jupyter = "^1.1.1"
google-genai = "^1.10.0"
pillow = "^11.1.0"
google-adk = "0.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
