[project]
name = "zghost"
version = "0.1.0"
description = ""
authors = [
    {name = "jtott"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gcloud (>=0.18.3,<0.19.0)",
    "google-genai (>=1.7.0,<2.0.0)",
    "ipykernel (>=6.29.5,<7.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
