#!/bin/bash
# Auto-generated by Antigravity

# Check if .env exists
if [ ! -f trends_and_insights_agent/.env ]; then
  echo "Error: trends_and_insights_agent/.env not found."
  echo "Please create it with the required environment variables (see README.md)."
  exit 1
fi

# Run adk web
echo "Starting ADK Web Server..."
uv run --env-file trends_and_insights_agent/.env adk web .
