@startuml

' GCP_BRANDING_APPLIED
!theme materia
skinparam backgroundColor #F8F9FA
skinparam roundCorner 10
skinparam defaultFontName "Open Sans"
skinparam DefaultFontSize 12
skinparam Padding 10

skinparam database {
    BackgroundColor #FBBC05
    BorderColor #E0E0E0
    FontColor #000
    Shadowing false
}
skinparam component {
    BackgroundColor #4285F4
    BorderColor #E0E0E0
    FontColor #FFF
    Shadowing false
}
skinparam rectangle {
    BackgroundColor #EA4335
    BorderColor #E0E0E0
    FontColor #FFF
    Shadowing false
}
skinparam note {
    BackgroundColor #FFFFFF
    BorderColor #E0E0E0
    FontColor #000000
    Shadowing false
    BorderThickness 1
}
skinparam collections {
    BackgroundColor #34A853
    BorderColor #E0E0E0
    FontColor #FFF
    Shadowing false
}
skinparam state {
    BackgroundColor #4285F4
    BorderColor #E0E0E0
    FontColor #FFF
    Shadowing false
}
skinparam activity {
    BackgroundColor #4285F4
    BorderColor #E0E0E0
    FontColor #FFF
    Shadowing false
}
skinparam actor {
    BackgroundColor #FFFFFF
    BorderColor #4285F4
    FontColor #000
    Shadowing false
    BorderThickness 2
}
skinparam usecase {
    BackgroundColor #FBBC05
    BorderColor #E0E0E0
    FontColor #000
    Shadowing false
}
skinparam cloud {
    BackgroundColor #FFFFFF
    BorderColor #E0E0E0
    FontColor #000
    Shadowing false
}
skinparam frame {
    BackgroundColor #FFFFFF
    BorderColor #E0E0E0
    FontColor #000
    Shadowing false
}
skinparam package {
    BackgroundColor #F8F9FA
    BorderColor #CCCCCC
    FontColor #000
    Shadowing false
    BorderThickness 1
}
skinparam node {
    BackgroundColor #EA4335
    BorderColor #E0E0E0
    FontColor #FFF
    Shadowing false
}
skinparam queue {
    BackgroundColor #34A853
    BorderColor #E0E0E0
    FontColor #FFF
    Shadowing false
}


[A] -> [B]
@endum
